### ISSUE TITLE
Unknown features and some feature conflicts

### ISSUE THREAD

**Issue by kbatsuren** [unimorph/tur#2]
Hi @omagolda,

I have been trying to canonicalize Turkish data, but I found a few unknown tags, and some feature conflicts from `um-canonicalize` tool.
Unknown features are: `INFR` , `PERF`, `PRSP`, `NEC`.
Feature conflicts is between `HAB` and `PROG`. I assume here it should be HAB+PROG.

Also, I found set of person and number features, e.g., `1S`, `2S`,... , `3P`.  They should be `1;SG` `2;SG`, ..., `3;PL`.

Let me know if you need my help to convert these features.

**Comment by omagolda** [comment]
I've corrected most of the errors.
Things I could not correct:

- `INFR` if for the inferential mood. I saw it was named as a mood on https://unimorph.github.io/doc/unimorph-schema.pdf. But it actually doesn't include a feature for it. I used the abbreviation from https://en.wikipedia.org/wiki/Inferential_mood. I suggest adding this feature to the canonization script.
- The `1S` etc. are actually not features of the nouns, but of the person predicated (like in the Trukish word "kedisin" equivalent to English "You are a cat"). like in the sentence. The problem is that we have no complex feature for that (in the style of `ARGAC2S`), so it was split to an `LGSPEC1` feature and the sub-features are appearing separately. That's not a good solution, but I have no clear solution. Maybe replace `LGSPEC;2S` with `ARGNO2S`?
- Also, I did correct and replaced `HAB;PROG` to `HAB+PROG`, but I think that the canonization script should allow more than one aspect feature.

Omer

**Comment by kbatsuren** [comment]
Thanks for very fast correction. :) 

> * `INFR` if for the inferential mood. I saw it was named as a mood on https://unimorph.github.io/doc/unimorph-schema.pdf. But it actually doesn't include a feature for it. I used the abbreviation from https://en.wikipedia.org/wiki/Inferential_mood. I suggest adding this feature to the canonization script.

We should add this feature in the document. Yes, let us stay with `INFR`. 

> * The `1S` etc. are actually not features of the nouns, but of the person predicated (like in the Trukish word "kedisin" equivalent to English "You are a cat"). like in the sentence. The problem is that we have no complex feature for that (in the style of `ARGAC2S`), so it was split to an `LGSPEC1` feature and the sub-features are appearing separately. That's not a good solution, but I have no clear solution. Maybe replace `LGSPEC;2S` with `ARGNO2S`?

I see. I think replacing them with `ARGNO2S` makes a lot of sense to me since this type of features are described in the original unimorph documentation.

You can close this issue. :) 

Huygaa
